
name: Unity CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run EditMode Tests
    runs-on: ubuntu-latest
    container:
      image: unityci/editor:ubuntu-6000.1.2f1-linux-il2cpp-3.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: game-ci/unity-activate@v2
        with:
          unityVersion: 2022.3.42f1

      - name: Run EditMode Tests
        uses: game-ci/unity-test-runner@v2
        with:
          unityVersion: 2022.3.42f1
          testMode: editmode