
name: Unity CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run EditMode Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Activate Unity
        uses: game-ci/unity-activate@v4
        with:
          unityVersion: 6000.1.2f1
          personalLicense: ${{ secrets.UNITY_LICENSE }}

      - name: Run EditMode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          unityVersion: 6000.1.2f1
          testMode: editmode